import logging
from dataclasses import dataclass, field

from Simulator.scripts.core.entities import Order, Task
from Simulator.scripts.core.warehouse import Warehouse
from Simulator.scripts.core.events import EventQueue, EventType, Event
from Simulator.scripts.sim import event_handler as eh


@dataclass
class Simulator:
    """
    Core discrete-event simulation engine managing event scheduling and execution.

    Attributes
    ----------
    clock : float                     Current simulation time.
    optimization : bool               If True, use optimization-based decisions; otherwise use heuristic policies.
    warehouse : Warehouse             Warehouse environment.
    event_queue : EventQueue          Priority queue of scheduled events.

    arrived_orders : list[Order]      Orders that have entered the system.
    scheduled_tasks : list[Task]      Tasks generated by optimizer/policies.
    """

    clock: float
    optimization: bool
    warehouse: Warehouse
    event_queue: EventQueue

    arrived_orders: list[Order] = field(default_factory=list)
    scheduled_tasks: list[Task] = field(default_factory=list)

    # DISPATCH TABLE
    def _build_dispatch(self):
        return {
            EventType.ARRIVAL_ORDER: eh.arrival_order,
            EventType.RUN_OPTIMIZER: eh.run_optimizer,
            EventType.RELEASE_TASK: eh.release_task,
            EventType.START_TASK: eh.start_task,
            EventType.ARRIVAL_POD_WST: eh.arrival_pod_wst,
            EventType.OPEN_ORDER: eh.open_order,
            EventType.START_PICKING: eh.start_picking,
            EventType.END_PICKING: eh.end_picking,
            EventType.CLOSE_ORDER: eh.close_order,
            EventType.RETURN_POD: eh.return_pod,
        }
    

    def run(self, time_horizon: float) -> None:
        """Run the simulation until the given time horizon."""

        logging.info("\n*********************************\nSTART SIMULATION...\n")

        dispatch = self._build_dispatch()

        # Schedule first event
        self.event_queue.schedule(time=1e-8, type=EventType.ARRIVAL_ORDER)

        # MAIN DES LOOP 
        while not self.event_queue.is_empty() and self.clock < time_horizon:

            # Retrievent next event to process
            event_to_process = self.event_queue.pop()
            self.clock = event_to_process.time

            logging.info(f"CLOCK = {self.clock:.4f} --> processing {event_to_process.type}")

            # Process event
            self._process_event(event_to_process, dispatch)

        logging.info("\nEND SIMULATION\n")



    def _process_event(self, event: Event, dispatch: dict) -> None:
        """Dispatch event to the corresponding handler."""

        handler = dispatch.get(event.type)
        if handler is None:
            raise ValueError(f"Unhandled event type: {event.type}")

        # Call handler with full simulator context
        handler(event, self)