import logging
from dataclasses import dataclass, field
from numpy.random import Generator

from Simulator.scripts.core.entities import Order, Task, Event
from Simulator.scripts.core.warehouse import Warehouse
from Simulator.scripts.core.queues import PriorityQueue
from Simulator.scripts.sim import event_handler as eh
from Simulator.scripts.core.enums import OrderStatus, EventType, PodStatus
from Simulator.scripts.stat.StatManager import StatManager



class Simulator:
    """
    Core discrete-event simulation engine managing event scheduling and execution.

    Attributes
    ----------
    RANDOM_GENERATOR: Generator                             Istance of the numpy.random.Generator module to generate variables
    STAT_MANAGER: StatManager                               Istance of StatManager to manage the statistics
    order_gen_config : list[float]                          Contains the parameters for order generation 
                                                                [orders_per_hour, prob_1_item_order, geo_dist_param_order]

    current_time : float                                    Current simulation time.
    optimization_enabled : bool                             If True, use optimization-based decisions; otherwise use heuristic policies.
    warehouse_status : Warehouse                            Warehouse environment containing the info about pod, robot and workstation status.
    future_events : PriorityQueue                           Priority queue of scheduled events.

    orders_in_system : PriorityQueue                        Orders that have entered the system.
    scheduled_tasks: dict[int, PriorityQueue[Task]]         Tasks generated by optimizer divided by workstation_id.
    released_tasks : PriorityQueue                          Tasks released, generally released_task_capacity tasks per workstation are active simultaneosly.
    active_tasks : dict[int, Task]                          To track active tasks (task_id, Task)
    """

    def __init__(
        self,
        random_generator: Generator,
        order_gen_config: list[float],
        warehouse: Warehouse,
        optimization_enabled: bool = False
    ) -> None:
        
        self.RANDOM_GENERATOR = random_generator
        self.STAT_MANAGER = StatManager(warehouse, warm_up=10)

        self.order_gen_config = order_gen_config
        self.optimization_enabled = optimization_enabled
        self.warehouse_status = warehouse

        self.current_time = 0

        # Future events queue --> priority is determined by when events are scheduled but release 
        # task events have always the priority to avoid incostincies in tasks released.
        self.future_events: PriorityQueue[Event] = PriorityQueue(key=lambda e: (e.time, e.type != EventType.RELEASE_TASK))
        self.orders_counter = 0
        self.orders_in_system: PriorityQueue[Order] = PriorityQueue(
                                key=lambda o: (o.status != OrderStatus.BACKLOG, o.arrival_time), 
                                id_attr='order_id')
        
        self.task_counter = 0
        self.scheduled_tasks: dict[int, PriorityQueue[Task]] = {
                    ws.workstation_id: PriorityQueue(key=lambda t: t.priority, id_attr='task_id')
                    for ws in warehouse.workstations
                }
        self.released_tasks: PriorityQueue[Task] = PriorityQueue(
            key=lambda t: (self.warehouse_status.pods[t.pod_id].status != PodStatus.IDLE, t.priority),
            id_attr='task_id'
        )
        self.active_tasks: dict[int, Task] = dict()

        # Contatori per il riepilogo periodico
        self._event_count = 0
        self._closed_orders = 0


    # Dispatch table 
    def _build_dispatch(self):
        return {
            EventType.ARRIVAL_ORDER:  eh.arrival_order,
            EventType.RUN_OPTIMIZER:  eh.run_optimizer,
            EventType.RELEASE_TASK:   eh.release_task,
            EventType.START_TASK:     eh.start_task,
            EventType.ARRIVAL_POD_WST: eh.arrival_pod_wst,
            EventType.OPEN_ORDER:     eh.open_order,
            EventType.START_PICKING:  eh.start_picking,
            EventType.END_PICKING:    eh.end_picking,
            EventType.CLOSE_ORDER:    eh.close_order,
            EventType.RETURN_POD:     eh.return_pod,
        }


    # Run 
    def run(self, time_horizon: float) -> None:
        """Run the simulation until the given time horizon."""

        logging.info("\n")
        logging.info("=============================================")
        min, sec = divmod(time_horizon, 60)
        hours, min = divmod(min, 60)
        logging.info("  START SIMULATION ... {TIME HORIZON  = %02d:%02d:%02d} ", 
                     hours, min, sec)
        

        dispatch = self._build_dispatch()

        e = Event(time=1e-8, type=EventType.ARRIVAL_ORDER)
        self.future_events.push(item=e)

        self.current_time = 0
        while not self.future_events.is_empty() and self.current_time < time_horizon:

            event_to_process = self.future_events.pop()
            self.current_time = event_to_process.time
            self._event_count += 1

            min, sec = divmod(self.current_time, 60)
            hours, min = divmod(min, 60)
            logging.debug("")
            logging.debug(
                "   EVENT NUM %-4d  current_time = %02d:%02d:%02d   %-20s  [number of future events = %d]",
                self._event_count,
                hours, min, sec,
                event_to_process.type.name,
                len(self.future_events)
            )

            self._process_event(event_to_process, dispatch)

        logging.info("\n")
        logging.info("  END SIMULATION.")        

        logging.info("\n")
        logging.info("writing Statistics Report ... ")
        self.STAT_MANAGER.return_statistics()

        logging.info("Statistic Manager Resetted")
        self.STAT_MANAGER.reset_statistics()



    def _process_event(self, event: Event, dispatch: dict) -> None:
        """Dispatch event to the corresponding handler."""
        handler = dispatch.get(event.type)
        if handler is None:
            raise ValueError(f"Unhandled event type: {event.type}")
        handler(event, self)

