import logging
from dataclasses import dataclass, field
from numpy.random import Generator

from Simulator.scripts.core.entities import Order, Task, Event
from Simulator.scripts.core.warehouse import Warehouse
from Simulator.scripts.core.queues import PriorityQueue
from Simulator.scripts.sim import event_handler as eh
from Simulator.scripts.core.enums import OrderStatus, EventType, PodStatus


class Simulator:
    """
    Core discrete-event simulation engine managing event scheduling and execution.

    Attributes
    ----------
    GEN: Generator                                          Istance of the numpy.random.Generator module to generate variables
    ORDER_GEN_PARAMS : list[float]                          Contains the parameters for order generation 
                                                                [orders_per_hour, prob_1_item_order, geo_dist_param_order]


    clock : float                                           Current simulation time.
    optimization : bool                                     If True, use optimization-based decisions; otherwise use heuristic policies.
    warehouse : Warehouse                                   Warehouse environment.
    event_queue : PriorityQueue                             Priority queue of scheduled events.

    arrived_orders : PriorityQueue                          Orders that have entered the system.
    self.scheduled_tasks: dict[int, PriorityQueue[Task]]    Tasks generated by optimizer divided by workstation_id
    released_tasks : list[Task]                             Tasks released, generally WS_QUEUE_CAPACITY tasks per ws are active simultaneosly
    """

    def __init__(
        self,
        gen: Generator,
        order_gen_params: list[float],
        warehouse: Warehouse,
        optimization : bool = False
    ) -> None:
        
        self.RNG = gen
        self.order_gen_config = order_gen_params
        self.optimization_enabled = optimization
        self.warehouse_status = warehouse

        self.current_time = 0
        self.future_events: PriorityQueue[Event] = PriorityQueue(key=lambda e: e.time)
        self.orders_in_system: PriorityQueue[Order] = PriorityQueue(
                                key=lambda o: (o.status != OrderStatus.BACKLOG, o.arrival_time), 
                                id_attr='order_id')
        
        self.task_counter = 0
        self.scheduled_tasks: dict[int, PriorityQueue[Task]] = {
                    ws.workstation_id: PriorityQueue(key=lambda t: t.priority, id_attr='task_id')
                    for ws in warehouse.workstations
                }
        self.released_tasks: PriorityQueue[Task] = PriorityQueue(key=lambda t: (self.warehouse_status.pods[t.pod_id].status != PodStatus.IDLE, t.priority), id_attr='task_id')


    # DISPATCH TABLE
    def _build_dispatch(self):
        return {
            EventType.ARRIVAL_ORDER: eh.arrival_order,
            EventType.RUN_OPTIMIZER: eh.run_optimizer,
            EventType.RELEASE_TASK: eh.release_task,
            EventType.START_TASK: eh.start_task,
            EventType.ARRIVAL_POD_WST: eh.arrival_pod_wst,
            EventType.OPEN_ORDER: eh.open_order,
            EventType.START_PICKING: eh.start_picking,
            EventType.END_PICKING: eh.end_picking,
            EventType.CLOSE_ORDER: eh.close_order,
            EventType.RETURN_POD: eh.return_pod,
        }
    

    def run(self, time_horizon: float) -> None:
        """Run the simulation until the given time horizon."""

        logging.info("\n*********************************\nSTART SIMULATION...\n")

        dispatch = self._build_dispatch()

        # Schedule first event
        e = Event(time = 1e-8, type = EventType.ARRIVAL_ORDER)
        self.future_events.push(item= e)

        # MAIN DES LOOP 
        self.current_time = 0
        while not self.future_events.is_empty() and self.current_time < time_horizon:

            # Retrievent next event to process
            event_to_process = self.future_events.pop()
            self.current_time = event_to_process.time

            logging.info(
                "CLOCK = %.4f --> processing %s",
                self.current_time,
                event_to_process.type.name
                )
            
            # Process event
            self._process_event(event_to_process, dispatch)

        logging.info("\nEND SIMULATION\n")

        print(self.orders_in_system)



    def _process_event(self, event: Event, dispatch: dict) -> None:
        """Dispatch event to the corresponding handler."""

        handler = dispatch.get(event.type)
        if handler is None:
            raise ValueError(f"Unhandled event type: {event.type}")

        # Call handler with full simulator context
        handler(event, self)